In [0]:
cd drive/'My Drive'/'Machine Learning A to Z'/'Part 1 - Data Preprocessing'/

[Errno 2] No such file or directory: 'drive/My Drive/Machine Learning A to Z/Part 1 - Data Preprocessing/'
/content/drive/My Drive/Machine Learning A to Z/Part 1 - Data Preprocessing


In [0]:
ls

 categorical_data.py
 categorical-data.py
 categorical_data.R
 Data.csv
 data_preprocessing_template.py
 data_preprocessing_template.R
 missing_data.py
 missing-data.py
 missing_data.R
'Section 2 -------------------- Part 1 - Data Preprocessing --------------------'/


In [0]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [0]:
dataset = pd.read_csv('Data.csv')

In [0]:
print(dataset)

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes


In [0]:
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, 3].values
print(x)
print(y)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [0]:
from sklearn.impute import SimpleImputer

In [0]:
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')

In [0]:
imputer = imputer.fit(x[:, 1:3])

In [0]:
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [0]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


Encoding Categorical Data
1. Encoding the Independent Variable

In [0]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import LabelEncoder

To Understand why the following code is no longer working for categorical purposes. Visit [this](https://towardsdatascience.com/columntransformer-in-scikit-for-labelencoding-and-onehotencoding-in-machine-learning-c6255952731b) link. That will clarify "Use ColumnTransformer in SciKit instead of LabelEncoding and OneHotEncoding for data preprocessing in Machine Learning"

In [0]:
#labelencoder_X = LabelEncoder()
#X[:, 0] = labelencoder_X.fit_transform(X[:, 0])
#onehotencoder = OneHotEncoder(categorical_features = [0])
#X = onehotencoder.fit_transform(X).toarray()
# Encoding the Dependent Variable
#labelencoder_y = LabelEncoder()
#y = labelencoder_y.fit_transform(y)
ct = ColumnTransformer([('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x), dtype=np.float)
print(x.astype(int))

[[    1     0     0    44 72000]
 [    0     0     1    27 48000]
 [    0     1     0    30 54000]
 [    0     0     1    38 61000]
 [    0     1     0    40 63777]
 [    1     0     0    35 58000]
 [    0     0     1    38 52000]
 [    1     0     0    48 79000]
 [    0     1     0    50 83000]
 [    1     0     0    37 67000]]


In [0]:
y = LabelEncoder().fit_transform(y)
print(y)

[0 1 0 0 1 1 0 1 0 1]


In [0]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)
print(x_train.astype(int), y_train.astype(int))
print(x_test.astype(int), y_test.astype(int))

[[    0     1     0    40 63777]
 [    1     0     0    37 67000]
 [    0     0     1    27 48000]
 [    0     0     1    38 52000]
 [    1     0     0    48 79000]
 [    0     0     1    38 61000]
 [    1     0     0    44 72000]
 [    1     0     0    35 58000]] [1 1 1 0 1 0 0 1]
[[    0     1     0    30 54000]
 [    0     1     0    50 83000]] [0 0]


As we can see in the salary and age section. Values have significant difference between each other. So, mostly in euclidean distancing. root((x2^2-x1^2) - (y2^2 - y1^2)) salary square values will dominate and hence eliminate the worthfulness of age column. So, we require **Feature Scaling**. This brings all columns on the same ground. Sometimes we even need to feature scale dependant variable when we find a huge range. Besides problems based on euclidean distancing, we still require scaling because it plays a huge role fast calculation. There are two ways for feature scaling. 
1. Standardisation. (x - mean(x))/standard deviation(x)
2. Normalisation. (x - min(x))/(max(x) - min(x))

In [0]:
from sklearn.preprocessing import StandardScaler
sc_x = StandardScaler()
x_train = sc_x.fit_transform(x_train) #you need to both fit and transform here. 
x_test = sc_x.transform(x_test)
#HERE WE DO NOT REQUIRE TO FEATURE SCALE y_train and y_test AS IT'S DEPENDANT VARIABLE WITH JUST TWO VALUES 0 AND 1 (NOT MUCH HUGE VARYING RANGE.)
x_train_pd = pd.DataFrame(data=x_train, index=None, columns=None)
x_test_pd = pd.DataFrame(data=x_test, index=None, columns=None)
x_train_pd.describe()
print()
x_test_pd.describe()

0         1         2         3         4
count  2.0  2.000000  2.000000  2.000000  2.000000
mean  -1.0  2.645751 -0.774597  0.263068  0.619074
std    0.0  0.000000  0.000000  2.435130  2.150647
min   -1.0  2.645751 -0.774597 -1.458829 -0.901663
25%   -1.0  2.645751 -0.774597 -0.597881 -0.141295
50%   -1.0  2.645751 -0.774597  0.263068  0.619074
75%   -1.0  2.645751 -0.774597  1.124016  1.379442
max   -1.0  2.645751 -0.774597  1.984964  2.139811